
spring:
  application:
    name: interview-security
  api-docs:
    enabled: true   # 是否开启openapi文档
    path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui/index.html
      operationsSorter: method  # 接口按http方法排序
      tagsSorter: alpha         # tag按字母排序

jwt:
  secret: abcdefghijklmnopqabcdefghijklmnopqabcdefghijklmnopq
  access-expire-minutes: 30

# OIDC Provider：账号 user / password；客户端 oidc-client / secret
# 发现文档：http://127.0.0.1:8080/.well-known/openid-configuration

server:
  port: 8080
